"""
GitHub Agent — creates branches, commits code changes, and opens pull requests.
"""
import re
from datetime import datetime
from typing import Any, Optional
from app.services.github_service import GitHubService


def generate_branch_name(task_description: str) -> str:
    """Generate a clean branch name from task description."""
    slug = re.sub(r"[^a-z0-9\s-]", "", task_description.lower())
    slug = re.sub(r"\s+", "-", slug.strip())
    slug = slug[:50]
    ts = datetime.utcnow().strftime("%Y%m%d")
    return f"codepilot/{ts}/{slug}"


def generate_pr_description(
    task_description: str,
    plan: dict,
    review_result: dict,
    docs_result: dict,
) -> str:
    """Generate a rich PR description in Markdown."""
    score = review_result.get("overall_score", "N/A")
    verdict = review_result.get("verdict", "approve")
    verdict_emoji = "✅" if verdict == "approve" else "⚠️"

    issues_count = len(review_result.get("issues", []))
    changelog = docs_result.get("changelog_entry", "")

    return f"""## 🤖 CodePilot AI — Automated Pull Request

### 📋 Task
> {task_description}

### 🗺️ Execution Plan
{plan.get('task_summary', '')}

**Complexity:** {plan.get('complexity', 'medium')} | **Estimated Duration:** {plan.get('estimated_duration_minutes', '?')} min

### 📊 Code Review Summary
{verdict_emoji} **Verdict:** {verdict.replace('_', ' ').title()} | **Score:** {score}/100

| Dimension | Score |
|-----------|-------|
| Security | {review_result.get('dimensions', {}).get('security', {}).get('score', 'N/A')} |
| Performance | {review_result.get('dimensions', {}).get('performance', {}).get('score', 'N/A')} |
| Maintainability | {review_result.get('dimensions', {}).get('maintainability', {}).get('score', 'N/A')} |
| Test Coverage | {review_result.get('dimensions', {}).get('test_coverage', {}).get('score', 'N/A')} |

**Issues Found:** {issues_count}

### 📝 Changelog
{changelog}

### ✅ Checklist
- [x] Code generated by CodePilot AI
- [x] Automated tests written
- [x] Code review completed
- [x] Documentation updated
- [ ] Human approval required

---
*Generated by [CodePilot AI](https://github.com) — Autonomous Software Engineering Platform*
"""


async def run_github_agent(
    owner: str,
    repo: str,
    task_description: str,
    generated_code: dict[str, Any],
    plan: dict[str, Any],
    review_result: dict[str, Any],
    docs_result: dict[str, Any],
    github_token: Optional[str] = None,
    simulate: bool = False,
) -> dict[str, Any]:
    """
    Create a branch, commit code, and open a pull request.

    Args:
        owner: GitHub repo owner
        repo: GitHub repo name
        task_description: Original task
        generated_code: Codegen agent output
        plan: Planner agent output
        review_result: Reviewer agent output
        docs_result: Docs agent output
        github_token: GitHub API token
        simulate: If True, skip real API calls and return mock result

    Returns:
        Pull request information
    """
    branch_name = generate_branch_name(task_description)
    pr_title = f"[CodePilot] {task_description[:70]}"
    pr_description = generate_pr_description(task_description, plan, review_result, docs_result)

    if simulate or not github_token:
        # Return simulated PR for demo/development
        return {
            "simulated": True,
            "branch_name": branch_name,
            "pr_title": pr_title,
            "pr_description": pr_description,
            "files_changed": [f["path"] for f in generated_code.get("files", [])],
            "pr_url": f"https://github.com/{owner}/{repo}/pull/42",
            "pr_number": 42,
            "status": "pending_approval",
        }

    try:
        gh = GitHubService(token=github_token)

        # Get default branch SHA
        default_branch = "main"
        sha = await gh.get_default_branch_sha(owner, repo, default_branch)

        # Create branch
        await gh.create_branch(owner, repo, branch_name, sha)

        # Create PR
        pr = await gh.create_pull_request(
            owner=owner,
            repo=repo,
            title=pr_title,
            body=pr_description,
            head=branch_name,
            base=default_branch,
        )

        return {
            "simulated": False,
            "branch_name": branch_name,
            "pr_title": pr_title,
            "pr_description": pr_description,
            "files_changed": [f["path"] for f in generated_code.get("files", [])],
            "pr_url": pr.get("html_url"),
            "pr_number": pr.get("number"),
            "status": "open",
        }

    except Exception as e:
        return {
            "simulated": True,
            "error": str(e),
            "branch_name": branch_name,
            "pr_title": pr_title,
            "pr_description": pr_description,
            "files_changed": [f["path"] for f in generated_code.get("files", [])],
            "status": "error",
        }
